services:
  app:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: url-shortener-mongodb
    networks:
      - app-network
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
