services:
  frontend:
    container_name: url-shortener-frontend
    build:
      context: ..
      dockerfile: ../Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/frontend
      - /usr/src/frontend/node_modules
    command: npm run dev
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    container_name: url-shortener-backend
    build:
      context: ..
      dockerfile: ../Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/backend
      - /usr/src/backend/node_modules
    command: npm run start:dev
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: url-shortener-mongodb
    networks:
      - app-network
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
